import type { Metadata } from "next";
import { Libre_Baskerville, Archivo } from "next/font/google";
import { Header } from "@/components/layout/header";
import "./globals.css";

const libre = Libre_Baskerville({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-libre",
});

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Bronze Lake Consulting",
  description: "Generated by create next app",
};

const nav_items = [
  { title: "About", href: "/about" },
  { title: "Growth Strategy", href: "/growth-strategy" },
  { title: "Digital Growth", href: "/digital-growth" },
  { title: "Technology Automation", href: "/technology-automation" },
  { title: "Reporting Analytics", href: "/reporting-analytics" },
  { title: "Contact", href: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre.variable} ${archivo.variable} antialiased`}
      >
        <Header navItems={nav_items} />
        {children}
      </body>
    </html>
  );
}
